import { StudioState } from '../types/studio';

export interface TemplatePreset {
  id: string;
  title: string;
  desc: string;
  thumbnail?: string;
  category: 'product' | 'social' | 'desktop' | 'mobile';
  state: Partial<StudioState>;
}

export const TEMPLATE_PRESETS: TemplatePreset[] = [
  // Product Presets
  {
    id: 'p1',
    title: 'Product Launch',
    desc: 'Floating shadow with soft gradient',
    category: 'product',
    thumbnail:
      'https://res.cloudinary.com/dbb1msinp/image/upload/v1786072101/morphic-cms-media/main-workspace/i7bem46043hcumfjrxej.webp',
    state: {
      imageName: 'Shotage',
      imageSrc:
        'https://res.cloudinary.com/dbb1msinp/image/upload/v1786071922/morphic-cms-media/main-workspace/zoipgvvuxigewg1oqdot.webp',
      urlText: 'shotage.studio',
      layoutCount: 1,
      aspectRatio: '16:9',
      frameType: 'safari-dark',
      shadow: 'floating',
      backgroundType: 'gradient',
      gradient: {
        color1: '#ffafcc',
        color2: '#bde0fe',
        angle: 135,
      },
      padding: 48,
      borderRadius: 16,
      zoom: 110,
    },
  },
  {
    id: 'p2',
    title: 'SaaS Hero Banner',
    desc: 'Minimalist clean border',
    category: 'product',
    thumbnail:
      'https://res.cloudinary.com/dbb1msinp/image/upload/v1786065136/morphic-cms-media/main-workspace/hhuuxm33fwb0epjn4pww.png',
    state: {
      imageName: 'Morphic CMS',
      imageSrc:
        'https://res.cloudinary.com/dbb1msinp/image/upload/v1786064269/morphic-cms-media/main-workspace/fujtd3cv7kjnccal6iz4.webp',
      layoutCount: 1,
      aspectRatio: '16:9',
      frameType: 'frameless',
      framelessStyle: 'glass-dark',
      shadow: 'none',
      backgroundType: 'linearSwatches',
      linearSwatchesPreset: 'ls-3',
      padding: 56,
      borderRadius: 20,
      zoom: 120,
      offsetY: 60,
    },
  },
  {
    id: 'p3',
    title: 'Product Spotlight',
    desc: 'Big product with lens blur',
    category: 'product',
    thumbnail:
      'https://res.cloudinary.com/dbb1msinp/image/upload/v1786196641/morphic-cms-media/main-workspace/m8mdzidpyhrqsqumeqev.webp',
    state: {
      imageName: 'Morphic CMS Dashboard',
      imageSrc:
        'https://res.cloudinary.com/dbb1msinp/image/upload/v1786196378/morphic-cms-media/main-workspace/lxdx9fivbrgacnooddid.webp',
      layoutCount: 1,
      aspectRatio: '16:9',
      frameType: 'frameless',
      framelessStyle: 'glass-dark',
      backgroundType: 'linearSwatches',
      linearSwatchesPreset: 'ls-15',
      bgBlur: 4,
      lensBlurEnabled: true,
      lensBlurRadius: 45,
      lensBlurAmount: 12,
      padding: 56,
      borderRadius: 20,
      zoom: 175,
      rotateX: 30,
      rotateY: 5,
      slot1Rotate: -30,
      offsetX: 82,
      offsetY: 20,
    },
  },

  // Social Media Presets
  {
    id: 's1',
    title: 'Product Showoff',
    desc: 'Safari dark browser on linear swatch background',
    category: 'social',
    thumbnail:
      'https://res.cloudinary.com/dbb1msinp/image/upload/v1786677298/morphic-cms-media/main-workspace/a9mc22vpdynjsrai8rae.png',
    state: {
      imageName: 'Shotage Studio',
      imageSrc:
        'https://res.cloudinary.com/dbb1msinp/image/upload/v1786677596/morphic-cms-media/main-workspace/tn9z5epee7rhzjusopd2.webp',
      layoutCount: 1,
      mediaType: 'image',
      layoutPreset: 'side-by-side',
      zoom: 182,
      slot2Zoom: 70,
      previewCanvasZoom: 103,
      alignment: 'center',
      padding: 48,
      borderRadius: 0,
      framelessStyle: 'default',
      shadow: 'floating',
      shadowOverlay: 'none',
      shadowOverlayOpacity: 85,
      shadowOverlayPosition: 'above',
      hideMockup: false,
      frameType: 'safari-dark',
      samsungStatusBar: 'none',
      iphoneStatusBar: 'none',
      urlText: 'shotage.studio',
      secondUrlText: 'shotage.app/demo',
      backgroundType: 'linearSwatches',
      linearSwatchesPreset: 'ls-2',
      backgroundColor: '#0f172a',
      bgGrain: 0,
      aspectRatio: 'ig-post',
      rotateX: 0,
      rotateY: 0,
      skewX: 0,
      skewY: 0,
      slot1Rotate: 0,
      slot2Rotate: 0,
      perspective: 1000,
      offsetX: 121,
      offsetY: 78,
      slot2OffsetX: 0,
      slot2OffsetY: 0,
      textLayers: [
        {
          id: 'text-1786675059956',
          text: 'It Off',
          fontFamily: 'Montserrat',
          fontSize: 45,
          fontWeight: '600',
          fontStyle: 'normal',
          color: '#f0f0f0',
          textAlign: 'center',
          x: -36,
          y: -214,
          shadow: false,
          opacity: 100,
          rotation: 0,
          pitch: 0,
          yaw: 0,
          skewX: 0,
          skewY: 0,
          position: 'above',
          name: '',
          visible: true,
          locked: false,
        },
        {
          id: 'text-1786675171336',
          text: 'Show',
          fontFamily: 'Montserrat',
          fontSize: 45,
          fontWeight: '700',
          fontStyle: 'normal',
          color: '#d4c0ae',
          textAlign: 'center',
          x: -166,
          y: -214,
          shadow: false,
          opacity: 100,
          rotation: 0,
          pitch: 0,
          yaw: 0,
          skewX: 0,
          skewY: 0,
          position: 'above',
          name: '',
          visible: true,
          locked: false,
          gradient: null,
        },
        {
          id: 'text-1786675489301',
          text: 'Turn your ideas into something worth\n showing off. Bring your creativity \nto life and share \nwhat you’ve created.',
          fontFamily: 'Outfit',
          fontSize: 13,
          fontWeight: '300',
          fontStyle: 'normal',
          color: '#ffffff',
          textAlign: 'left',
          x: -122,
          y: -149,
          shadow: false,
          opacity: 100,
          rotation: 0,
          pitch: 0,
          yaw: 0,
          skewX: 0,
          skewY: 0,
          position: 'above',
          name: '',
          visible: true,
          locked: false,
        },
      ],
    },
  },

  // Desktop Presets
  {
    id: 'd1',
    title: 'MacBook Showcase',
    desc: 'MacBook Pro frame with shadow overlay',
    category: 'desktop',
    thumbnail:
      'https://res.cloudinary.com/dbb1msinp/image/upload/v1786071490/morphic-cms-media/main-workspace/gfca5l0bz3jgdytpqong.webp',
    state: {
      imageName: 'MacBook Showcase',
      imageSrc:
        'https://res.cloudinary.com/dbb1msinp/image/upload/v1786071336/morphic-cms-media/main-workspace/tzrxid7ct4heg6bi2dal.webp',
      layoutCount: 1,
      aspectRatio: '16:9',
      frameType: 'macbookair13',
      shadow: 'floating',
      backgroundType: 'gradient',
      gradient: {
        color1: '#4f46e5',
        color2: '#06b6d4',
        angle: 145,
      },
      bgBlur: 10,
      padding: 24,
      zoom: 120,
      shadowOverlay: 'shadow-overlay-4',
      shadowOverlayOpacity: 80,
      shadowOverlayPosition: 'behind',
    },
  },
  {
    id: 'd2',
    title: 'Safari Browser',
    desc: 'Light mode browser frame with 16:9',
    category: 'desktop',
    thumbnail:
      'https://res.cloudinary.com/dbb1msinp/image/upload/v1786072836/morphic-cms-media/main-workspace/xa03dulv4akqsvzwhvuo.webp',
    state: {
      imageName: 'Heylookatme',
      imageSrc:
        'https://res.cloudinary.com/dbb1msinp/image/upload/v1786072579/morphic-cms-media/main-workspace/shwvbourn65mx53xfgxs.webp',
      layoutCount: 1,
      aspectRatio: '16:9',
      frameType: 'safari-light',
      urlText: 'heylookat.me',
      shadow: 'medium',
      shadowOverlay: 'shadow-overlay-2',
      shadowOverlayOpacity: 20,
      shadowOverlayPosition: 'above',
      backgroundType: 'linearSwatches',
      linearSwatchesPreset: 'ls-18',
      radiantPreset: 'radiant-1',
      padding: 48,
    },
  },

  // Mobile Presets
  {
    id: 'm1',
    title: 'iPhone 15',
    desc: '9:16 vertical mockup',
    category: 'mobile',
    thumbnail:
      'https://res.cloudinary.com/dbb1msinp/image/upload/v1786067990/morphic-cms-media/main-workspace/dd9sliakqee31zdd9bw5.jpg',
    state: {
      imageName: 'iPhone 15 Wallpaper',
      imageSrc:
        'https://res.cloudinary.com/dbb1msinp/image/upload/v1786067702/morphic-cms-media/main-workspace/i4ncoex9kj3xhtprt3tv.webp',
      layoutCount: 1,
      aspectRatio: '9:16',
      frameType: 'iphone',
      iphoneStatusBar: 'light',
      shadow: 'floating',
      backgroundType: 'gradient',
      gradient: {
        color1: '#eef2f3',
        color2: '#8e9eab',
        angle: 135,
      },
      zoom: 140,
      padding: 48,
    },
  },
  {
    id: 'm2',
    title: 'Instagram Post',
    desc: 'Image with Instagram frame',
    category: 'mobile',
    thumbnail:
      'https://res.cloudinary.com/dbb1msinp/image/upload/v1786069988/morphic-cms-media/main-workspace/rcdfwjknm55etkbfl8ki.jpg',
    state: {
      imageName: 'Instagram Post',
      imageSrc:
        'https://res.cloudinary.com/dbb1msinp/image/upload/v1786069519/morphic-cms-media/main-workspace/uytw1blb9mxos5kwsck0.webp',
      layoutCount: 1,
      aspectRatio: 'ig-post',
      frameType: 'instagram',
      shadow: 'medium',
      backgroundType: 'confetti',
      confettiPreset: 'confetti-6',
      padding: 80,
    },
  },
  {
    id: 'm3',
    title: 'Dual Mobile Rotated',
    desc: 'Side-by-side dual mockup with 45° rotation',
    category: 'mobile',
    thumbnail:
      'https://res.cloudinary.com/dbb1msinp/image/upload/v1786067093/morphic-cms-media/main-workspace/d0m3tx6b6qnw33bzarek.jpg',
    state: {
      imageName: 'Mobile Rotated 1',
      imageSrc:
        'https://res.cloudinary.com/dbb1msinp/image/upload/v1786066146/morphic-cms-media/main-workspace/wjzlqpem7pnpfhvwha1v.webp',
      secondImageName: 'Mobile Rotated 2',
      secondImageSrc:
        'https://res.cloudinary.com/dbb1msinp/image/upload/v1786066363/morphic-cms-media/main-workspace/bbuqgjwna2khp9kq2i9e.webp',
      layoutCount: 2,
      layoutPreset: 'side-by-side',
      frameType: 'iphone14pro',
      zoom: 170,
      slot2Zoom: 170,
      slot1Rotate: -45,
      slot2Rotate: 135,
      offsetX: -68,
      offsetY: 68,
      slot2OffsetX: 74,
      aspectRatio: '9:16',
      shadow: 'soft',
      backgroundType: 'gradient',
      gradient: {
        color1: '#cdb4db',
        color2: '#a2d2ff',
        angle: 135,
      },
      padding: 32,
      shadowOverlay: 'shadow-overlay-3',
      shadowOverlayOpacity: 80,
    },
  },
];
